### ISSUE TITLE
Is there any method to get currently playing url?

### ISSUE THREAD

**Issue by SimonPeter1909** [jeromexiong/audio_manager#1]
The Audio Manager I have been waiting for a long time. It's Perfect. Thank you @jeromexiong.

But,
I need to get the URL of the currently playing audio. I can't find any method for that.

**Comment by jeromexiong** [comment]
You can record the current playback information when calling the start method or wait for me to add a method

**Comment by cstsortan** [comment]
Is there any further information on this? Should I save the current playable item in something like prefs in order to show what's the current player state when app reloads? This is most important on android, where back button "closes" the app
