### ISSUE TITLE
App crashes on iOS when Preloading other playback information

### ISSUE THREAD

**Issue by Veerse** [jeromexiong/audio_manager#10]
Hello

The app crashes when I am currently playing an audio file, and I try to Preload other audio info with `AudioManager.instance.start(...)` to play an other audio (on iOS only (real device and simulator))

What is the proper way to stop the currently played audio and then start a new one (from a different URL) when a button is clicked for instance ?

**Comment by Veerse** [comment]
<img width="1174" alt="Capture d’écran 2020-03-31 à 15 05 10" src="https://user-images.githubusercontent.com/20816459/78029569-2059cf00-7361-11ea-9c58-5f690661f77a.png">

Here's the message I get

**Comment by jeromexiong** [comment]
Are you sure the version is v0.5.3+2?  If yes, please provide detailed log and running environment
