### ISSUE TITLE
playing local file

### ISSUE THREAD

**Issue by mohamedrafatfcih** [jeromexiong/audio_manager#16]
Playing local file ( file://${file.path} ) doesn't work and crashes the app.
can you fix it ?

**Comment by jeromexiong** [comment]
are you sure the local file existed?

**Comment by mohamedrafatfcih** [comment]
yes, it totally crash the app in the IOS side

**Comment by mohamedrafatfcih** [comment]
I did a fix for this you can check the pull requests section

**Comment by jeromexiong** [comment]
tks

**Comment by mohamedrafatfcih** [comment]
welcome
