### ISSUE TITLE
Change android notification icons

### ISSUE THREAD

**Issue by michaelspeedcode** [jeromexiong/audio_manager#18]
Thank you for this lib, it's really helped me!

I was wondering if it's possible to change the icons on the notification? And how can I remove the 'next' button if there's only one item in the queue? 
Thanks again!

**Comment by jeromexiong** [comment]
sorry for that, but this feature cannot be custom, you can fork project branch to modify

**Comment by mohamedrafatfcih** [comment]
Hi, 
I have an error from android whatever I passed value cover parameter or not and audio not play

 java.io.FileNotFoundException: flutter_assets/assets/ic_launcher.png
W/System.err(29316): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
W/System.err(29316): 	at android.content.res.AssetManager.open(AssetManager.java:750)
W/System.err(29316): 	at android.content.res.AssetManager.open(AssetManager.java:727)

**Comment by mohamedrafatfcih** [comment]
> Hi,
> I have an error from android whatever I passed value cover parameter or not and audio not play
> 
> java.io.FileNotFoundException: flutter_assets/assets/ic_launcher.png
> W/System.err(29316): at android.content.res.AssetManager.nativeOpenAsset(Native Method)
> W/System.err(29316): at android.content.res.AssetManager.open(AssetManager.java:750)
> W/System.err(29316): at android.content.res.AssetManager.open(AssetManager.java:727)
thanks I missed something
