### ISSUE TITLE
Timestamp for iOS/android

### ISSUE THREAD

**Issue by ohnovurzaagain** [jeromexiong/audio_manager#20]
Hello what’s up and great plugin, love it!

I saw in my emulator iOS and Android controllcenter view timestamp of Song which is played.

Can you change timestamp to something more compact and beautiful like this for example:

At the moment: 0:00:000000 - 0:00:000000
To this: 0:00:0 - 0:00:0

**Comment by jeromexiong** [comment]
The project is dedicated to playing audio and returning time display to `Duration` format in a unified way, which is maintained by developers themselves
