### ISSUE TITLE
Highlight currently playing Song in list

### ISSUE THREAD

**Issue by md186** [jeromexiong/audio_manager#21]
If I set color for index on currently playing Song everything works fine. If I go to next song via Notification Center on iOS/android, Song index doesn’t refresh highlighted Song index.

Im using Audiomanager.instance.curIndex for displaying highlighted song, but it doesn’t refresh if you go to next song via Notification Center iOS/android

**Comment by jeromexiong** [comment]
you can clone this project and run the example. There is no problem in my side
