### ISSUE TITLE
How can i reset AudioManager.instance state?

### ISSUE THREAD

**Issue by phanbaohuy96** [jeromexiong/audio_manager#24]
Currently, I use this plugin to play a single audio.  I start with a screen suck as player screen then if the user finished this screen the audio with stop too. if I start that screen again and play the same audio with previously but AudioManager not working for this case.
another case:
- Android: if I close play by media notification and play again with the same audio  then AudioManager not working too ( for this case: how can I listen close event by media notification for reset AudioManager.instance state or something else)

Thanks a lot.

**Comment by jeromexiong** [comment]
You need to use `provider` as the global only player
