### ISSUE TITLE
iOS - Trying to change index while loading from url - getting error 'AVPlayerItem was deallocated while key value observers were still registered with it.'

### ISSUE THREAD

**Issue by manojvsp12** [jeromexiong/audio_manager#27]
Trying to change index as provided index url is taking too much time to load. App crashed with below error.

AVPlayerItem was deallocated while key value observers were still registered with it.

Device: iPad iOS 9.3.5

**Comment by jeromexiong** [comment]
can you show me more info? Generally speaking, it is mainly time-consuming to load network resources
