### ISSUE TITLE
Crush while playing androin audio in offline

### ISSUE THREAD

**Issue by cr0manty** [jeromexiong/audio_manager#28]
W/System.err(16607): java.net.UnknownHostException: Unable to resolve host "pbs.twimg.com": No address associated with hostname
W/System.err(16607): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
W/System.err(16607): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/System.err(16607): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
W/System.err(16607): 	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
W/System.err(16607): 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
W/System.err(16607): 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
W/System.err(16607): 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
W/System.err(16607): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
W/System.err(16607): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
W/System.err(16607): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
W/System.err(16607): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
W/System.err(16607): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
W/System.err(16607): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
W/System.err(16607): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
W/System.err(16607): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
W/System.err(16607): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
W/System.err(16607): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
W/System.err(16607): 	at cc.dync.audio_manager.MediaPlayerService.getBitmapFromUrl(MediaPlayerService.java:281)
W/System.err(16607): 	at cc.dync.audio_manager.MediaPlayerService.lambda$updateCover$0$MediaPlayerService(MediaPlayerService.java:236)
W/System.err(16607): 	at cc.dync.audio_manager.-$$Lambda$MediaPlayerService$JSqC9Btt6eaYwxL-BEuUfDf3fYc.run(Unknown Source:4)
W/System.err(16607): 	at java.lang.Thread.run(Thread.java:919)
W/System.err(16607): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/System.err(16607): 	at libcore.io.Linux.android_getaddrinfo(Native Method)
W/System.err(16607): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
W/System.err(16607): 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
W/System.err(16607): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
W/System.err(16607): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
W/System.err(16607): 	... 20 more
E/AndroidRuntime(16607): FATAL EXCEPTION: Thread-3
E/AndroidRuntime(16607): Process: music.fox_music, PID: 16607
E/AndroidRuntime(16607): java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
E/AndroidRuntime(16607): 	at cc.dync.audio_manager.MediaPlayerService.getBitmapFromUrl(MediaPlayerService.java:290)
E/AndroidRuntime(16607): 	at cc.dync.audio_manager.MediaPlayerService.lambda$updateCover$0$MediaPlayerService(MediaPlayerService.java:236)
E/AndroidRuntime(16607): 	at cc.dync.audio_manager.-$$Lambda$MediaPlayerService$JSqC9Btt6eaYwxL-BEuUfDf3fYc.run(Unknown Source:4)
E/AndroidRuntime(16607): 	at java.lang.Thread.run(Thread.java:919)
I/Process (16607): Sending signal. PID: 16607 SIG: 9
Lost connection to device.

**Comment by md186** [comment]
Yes, same is happening on iOS!
