### ISSUE TITLE
Buffering Songs on iOS not working immediately

### ISSUE THREAD

**Issue by md186** [jeromexiong/audio_manager#29]
Hello, buffering on iOS with WLAN off is not working as expected.  (Please check it on android too) I tested it on several real iPhones, if WLAN is off and I use LTE or other mobile network, song starts playing first, when complete song is initialized, and then it starts buffering at very last. This causes waiting for song start playing very long time. It is wrong order. If wlan is on, song directly starts playing and buffering like it should

Please fix this on WLAN off mode, this is really annoying. Thank you!

**Comment by jeromexiong** [comment]
hi，guys，I test the buffering loading locally. Whether WLAN or LTE, it can be buffering normally. Even if the network is switched in the buffer, it will still be loaded. Have you tried to change the audio url?

**Comment by md186** [comment]
Hello thank you for checking, I’m using your plugin in my app, with wlan everything is working fine the queue is:

loading list -> loading selected song and playing and buffering. 

Without wlan it is the following:

Loading list -> loading selected song until the complete song is loaded -> then after loading it starts buffering.

Buffering and playing song at the same time is only working with wlan on. With wlan of it waits until the complete song is loaded and THEN it starts playing.

I have only network songs in the list no local Songs. Maybe that’s the issue.

**Comment by md186** [comment]
@jeromexiong it seems like this happens with network songs, did you find something out? 🙄

**Comment by md186** [comment]
@jeromexiong well after some reasearch it seems like in general starting network song is slightly slower than on android player.  I found this code example here as it was an issue of another media player library, maybe it helps you making the swift player faster:

```
AVPlayer *player = playerInfo[@"player"];

float playbackRate = [playerInfo[@"rate"] floatValue];

if (@available(iOS 10.0, *)) {
    [player playImmediatelyAtRate:playbackRate];
} else {
    [player play];
}
```

**Comment by md186** [comment]
@jeromexiong 

Would be nice if you can implement it, im not able to test it my coding experience is not good enough i dont know how to get it working, never did it before..
But in every flutter audio library this was an issue which was solved this way.

```
if #available(iOS 10.0, *) {
    player?.playImmediately(atRate: 1.0)
} else {
    player?.play()
}
```

Maybe better define the rate with 1.0? I don't know if its better in your code or no.

______________

Also please do me a favor and check this:

Try to set automaticallyWaitsToMinimizeStalling property of AVPlayer to NO in order to start playback immediately.

```
_avPlayer = [[AVPlayer alloc]init]; //WithPlayerItem:_avPlayerItem];
_avPlayer.automaticallyWaitsToMinimizeStalling = NO;
```
But if sufficient content is not available for playing then player might stall.

Apple documentation: https://developer.apple.com/reference/avfoundation/avplayer/1643482-automaticallywaitstominimizestal.

The above code also was something I found on stackoverflow which might be useful for performance on ios network songs.

I'm excited if you put all the stuff in the next plugin version!

**Comment by md186** [comment]
Closed since @jeromexiong fixed it with `playImmediatelyAtRate` and `automaticallyWaitsToMinimizeStalling`

Playing network songs on ios with wlan or lte or whatever is super fast now ! 👌

**Comment by jeromexiong** [comment]
enjoy your job 🎉
