### ISSUE TITLE
Does this player supports only .mp3?

### ISSUE THREAD

**Issue by SimonPeter1909** [jeromexiong/audio_manager#3]
Does this player support M4A format? the player is not working when I tried to play an M4A URL.

**Comment by jeromexiong** [comment]
Audio playback is based on mediaplayer and supports m4a files

**Comment by SimonPeter1909** [comment]
ok. But `AudioManager.instance.isPlaying` is always returning false.

**Comment by jeromexiong** [comment]
That may be because the media resource failed to load, I need to add an error message.

Below is the log I printed
```
I/flutter (30621): buffering 100
I/flutter (30621): await -- true
I/flutter (30621): {url: https://fdfs.xmcdn.com/group45/M05/82/AB/wKgKjlt55kKRse-KADE6m6WsfuE514.m4a, title: title, desc: desc, cover: https://cdn.jsdelivr.net/gh/flutterchina/website@1.0/images/flutter-mark-square-100.png}
I/flutter (30621): await -- false
I/flutter (30621): await -- true
```
