### ISSUE TITLE
How to call the setupAudio() on a button press rather than in initState() ?

### ISSUE THREAD

**Issue by Maadhav** [jeromexiong/audio_manager#30]
I tried calling the setupAudio function from the example on button press but then it gives two types of errors, first: --stop and the second, await -false. Can you please show me what's the proper way of doing this?

**Comment by jeromexiong** [comment]
`Setupaudio` is to initialize audio data and set callback listener. If you want to click the button to play, please use the `start` method to play

**Comment by Maadhav** [comment]
Ya but then the following error comes:
--stop and nothing plays
Could pls give me a working example for this it would be a big help.
Thanks

**Comment by jeromexiong** [comment]
you must load audio resource first, then playOrPause and so on method is valid
```
// Initial playback. Preloaded playback information
AudioManager.instance
	.start(
		"assets/audio.mp3",
		"title",
		desc: "desc",
		cover: "assets/ic_launcher.png")
	.then((err) {
	print(err);
});
// must Initial playback
AudioManager.instance.playOrPause()
```

**Comment by Maadhav** [comment]
Ok will try and let u know, Thanks...

**Comment by Maadhav** [comment]
MissingPluginException(No implementation found for method currentVolume on channel audio_manager)
