### ISSUE TITLE
String Audio in Error - 媒体资源加载失败

### ISSUE THREAD

**Issue by joaowd** [jeromexiong/audio_manager#32]
I'm getting this error:

https://sentry.io/share/issue/aa20eef1c7214b939f382465d2fe9dae/

Can someone explain what is it ?

**Comment by md186** [comment]
when do you get this error? can you show some code? It means that loading of some mediafiles didnt work as expected.

**Comment by joaowd** [comment]
Thanks for the fast reply,

this is my code for the audio service:

[Gist Link](https://gist.github.com/joaowd/66d90a03c53ebf78cead828eb6fccacf)

**Comment by jeromexiong** [comment]
You don't need to call play at the same time as you call start. The difference between these two methods is that one can play a single and the other can play the data in the `audiolist`

**Comment by joaowd** [comment]
Oh alright, so should I only use start?

**Comment by jeromexiong** [comment]
yeah
