### ISSUE TITLE
**** Since 0.5.5 AVPlayer doesnt work correct anymore ****

### ISSUE THREAD

**Issue by md186** [jeromexiong/audio_manager#33]
Since the newest version, AVPlayer is totally broken. in 0.5.4+1 everything worked perfectly.

If you play next song, sometimes its not playing anymore because it jumps from one song to another, it is flicking all the time and it is changing the index randomly. if you go back in the app then, the selected item which is actually playing is jumping all the time.

Pls roll this back or fix it...!

video: https://streamable.com/5jskjy

**Comment by jeromexiong** [comment]
I have fixed this problem urgently at `0.5.5+1`. Sorry for the trouble

**Comment by md186** [comment]
@jeromexiong oh great thank you! 🙏
