### ISSUE TITLE
'void android.media.MediaPlayer.start()' on a null object reference when trying to play local files

### ISSUE THREAD

**Issue by papaibsow** [jeromexiong/audio_manager#37]
I/flutter ( 7308): status false
I/flutter ( 7308): AudioManagerEvents.start, AudioInfo{url: file:///storage/emulated/0/Android/data/com.mouridepro.android/files/mesaudios/Ahaazanil Baaqii.aac, title: Ahaazanil Baaqii, desc: enregistrement}
I/flutter ( 7308): start load data callback, curIndex is 0
V/AudioManagerPlugin( 7308): --stop
I/flutter ( 7308): Attempt to invoke virtual method 'void android.media.MediaPlayer.start()' on a null object reference

**Comment by jeromexiong** [comment]
Are you sure the file exists?

**Comment by papaibsow** [comment]
Yes of course



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by skabirgithub** [comment]
How did you fix?
