### ISSUE TITLE
Pause to enter the background, but when it comes back to the foreground, it starts playing automatically

### ISSUE THREAD

**Issue by hrongyong** [jeromexiong/audio_manager#39]
Pause to enter the background, but when it comes back to the foreground, it starts playing automatically

There are solutions：
https://www.jianshu.com/p/0eb4f84ef55b

But i can't understand it, it's up to you

**Comment by jeromexiong** [comment]
audio_ manager didn't listen to the foreground and background notifications

**Comment by hrongyong** [comment]
之前我发现切到后台后，播放停止（切之前是正在播放的）。
所以我打开了这个
![image](https://user-images.githubusercontent.com/37935622/85092159-b2180080-b21b-11ea-9906-7f79f85e42c3.png)
就可以正常的在后台播放音频了。
但是我发现，当我app在前台的时候暂停，然后切到后台，过了五分钟后再将app切回前台，音频会自动播放，我觉得这不是正常情况吧。。。
我查简书找到了上面那个。。。
（发中文没影响b格吧）

**Comment by jeromexiong** [comment]
@hrongyong 权限问题你可以查看`info.plist`和`AndroidManifest.xml`，至于五分钟暂停后自动播放问题没遇到
