### ISSUE TITLE
How to cancel Audio Manager loading resource

### ISSUE THREAD

**Issue by md186** [jeromexiong/audio_manager#46]
Hello @jeromexiong ,

I have a specific case, but who knows maybe someone else does need this information. In my app I have a carousel and each slide is showing an image and loading a song file. Now I can slide to right and left, but it only lets me slide if the song is initialized. I already tried AudioManager.instance.stop() and AudioManager.instance.playandpause() but it wont stop initializing the song.

I already connected all AudioManager events with providers, but I dont know how to make the loading process cancelling. Do you have any idea?

**Comment by jeromexiong** [comment]
@md186 you can invoke the `stop` method to release all resources. if it is not released, please check the demo and debug step by step

**Comment by md186** [comment]
@jeromexiong How to do this? Could you provide me code example? I tried AudioManager.instance.stop(); this doesnt work
