### ISSUE TITLE
Notification Panel still exits even after clearing the playlist

### ISSUE THREAD

**Issue by poonkuzhalik** [jeromexiong/audio_manager#51]
Hi,

I'm using version - 0.5.7+1 

While trying to support a 'clear playlist' functionality, I do the following steps

 await AudioManager.instance.stop();
 await AudioManager.instance.release();
 AudioManager.instance.audioList.clear();

But I still see the notification panel open with the last song, while the actual playlist is empty.
Also, click on the notification panel doesn't execute any operation.

Can you please let me know, if I'm missing any step or is it a bug to be handled?

Poongs

**Comment by vivekdhameliya2** [comment]
Same issue with me also, if you know any solution please help me..

**Comment by ManojDvs** [comment]
yes clicking on notification does not open the app for me, any solution for this.

**Comment by jeromexiong** [comment]
not supported yet. like #56
