### ISSUE TITLE
Local file coverUrl not working on Android

### ISSUE THREAD

**Issue by maciogg** [jeromexiong/audio_manager#52]
Hi
On Android coverUrl not working. 
I got exception
V/AudioManagerPlugin(17668): 播放错误:java.io.FileNotFoundException: file:///data/user/0/com.blizejprzedszkola.app.mojaplytoteka/app_flutter/covers/17_cover.jpg
and
 I/flutter (17668): AudioManagerEvents.error, java.io.FileNotFoundException: file:///data/user/0/com.blizejprzedszkola.app.mojaplytoteka/app_flutter/covers/17_cover.jpg
On iOS everything works fine.

**Comment by jeromexiong** [comment]
please make sure the `17_cover.jpg` file exist in device path

**Comment by DonAlex1897** [comment]
> please make sure the `17_cover.jpg` file exist in device path

I have the same problem. It doesn't understand the local path. I have checked multiple times and the path is correct. Also, it does not recognize my `http://10.0.2.2:5000/...` address, while it's reachable in other parts of code.

**Comment by PatriceVignola** [comment]
@DonAlex1897 @maciogg It's probably not relevant anymore for you, but I recently stumbled upon this issue and made a fork that fixes it: https://github.com/PatriceVignola/audio_manager I will keep the fork up until it's merged into upstream (at the very least). If it never gets merged, I guess I'll just keep the fork until the end of times 😄 The changes are pretty simple so you can make your own fork with the same changes if you want, and use somthing like this in `pubspec.yaml`:

```yaml
audio_manager:
    git:
      url: https://github.com/<github_username>/audio_manager
```

@jeromexiong I made a PR in case you're interested in merging it https://github.com/jeromexiong/audio_manager/pull/81

**Comment by jeromexiong** [comment]
fine 😃
