### ISSUE TITLE
failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by cth00** [jeromexiong/audio_manager#55]
I'm facing this issue, does anyone have any idea about this? I'm using android 10 and I guess that's the cause of error, I haven't tested on lower version.

V/MediaPlayer( 5886): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 5886): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/AudioManagerPlugin( 5886): --播放错误
V/AudioManagerPlugin( 5886): 播放错误:java.io.FileNotFoundException: /storage/emulated/0/Download/titliaan_.mp3: open failed: EACCES (Permission denied)
V/MediaPlayer( 5886): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 5886): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/AudioManagerPlugin( 5886): --stop

**Comment by jeromexiong** [comment]
You can refer to the demo, which is OK
