### ISSUE TITLE
On app load, the plugin stops any background audio?

### ISSUE THREAD

**Issue by stanojevicboban** [jeromexiong/audio_manager#57]
Hi, I have a flutter app where only a small part of it is using this component to reproduce audio file.

However, when I play music in a different app, and then load the app, the audio coming from another app is stopped. In the events in XCode I see 
` > > > > > Audio Route Changed`
output that is coming from the `AudioManager.swift`.

Is there a way to allow the background music to continue playing while the app is in foreground?

**Comment by FloPMT** [comment]
@jeromexiong I created PR #59 to fix this

**Comment by jeromexiong** [comment]
> @jeromexiong I created PR #59 to fix this

tks，but there are some small problems with your PR, so i would fix them without merging
