### ISSUE TITLE
Events repeat callbacks

### ISSUE THREAD

**Issue by AtixD** [jeromexiong/audio_manager#6]
I use your example, When call start method in instance, onEvent repeated callback.

flutter: AudioManagerEvents.timeupdate, {position: 2004, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 2004, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 2005, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 2005, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 2006, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 2006, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 2007, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 2007, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 2008, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 2008, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3001, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3002, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3002, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3003, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3003, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3004, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3004, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3004, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3005, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3005, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3006, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3006, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3007, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3007, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3008, duration: 372715}
flutter: AudioManagerEvents.timeupdate, {position: 3008, duration: 372715}
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false
flutter: AudioManagerEvents.playstatus, false

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale ru-RU)
    • Flutter version 1.12.13+hotfix.8 at /Users/reuf/development/flutter
    • Framework revision 0b8abb4724 (11 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

iOS 13.3

**Comment by jeromexiong** [comment]
Designed like this, callback progress events etc.

**Comment by AtixD** [comment]
@jeromexiong Event double call when start player again.
