### ISSUE TITLE
audio duration doesn't work if I have voice messages in chat

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [jeromexiong/audio_manager#66]
I have chat screen that have texts, photos and voices. when i send voice url to (start) method used same instance of audio manager and this give the duration of last voice message for all voice messages....
please I want to understand how to fix this.
thanks.

**Comment by jeromexiong** [comment]
so far, we can't play audio at the same time

**Comment by jeromexiong** [comment]
so far, we can't play audio at the same time
