### ISSUE TITLE
Url network files not opening some

### ISSUE THREAD

**Issue by kizinho** [jeromexiong/audio_manager#67]
It looks like it selecting different type of mp3, it is not downloading all link files over network

**Comment by jeromexiong** [comment]
Make sure the music files are supported by avplayer and mediaplayer

**Comment by kizinho** [comment]
![Screenshot_20210625-055540](https://user-images.githubusercontent.com/28742483/123371803-509b1800-d57a-11eb-9c02-fa57d69f3181.png)
![Screenshot_20210625-055518_Fidelity](https://user-images.githubusercontent.com/28742483/123371807-51cc4500-d57a-11eb-9192-1a234ab21742.png)

The network file will not load but from notification you can start playing the song
