### ISSUE TITLE
Issues on flutter 2.2.2

### ISSUE THREAD

**Issue by kizinho** [jeromexiong/audio_manager#68]
Android version 11, minisdk 23 and 30 
IOS no issues 

On android the song will be downloaded over internet but can't load it to the player instance but the song will be available from notification once click on play notification it will start playing .
![Screenshot_20210625-055518_Fidelity](https://user-images.githubusercontent.com/28742483/123506658-4bfb6000-d65d-11eb-8ba1-34e7ccba69bb.png)
![Screenshot_20210625-055540](https://user-images.githubusercontent.com/28742483/123506659-4d2c8d00-d65d-11eb-8476-6fe689becd31.png)

**Comment by JoelFickson** [comment]
I experience the same on Android

**Comment by kizinho** [comment]
No longer use the package
