### ISSUE TITLE
Audio automatically plays when the app is opened from background

### ISSUE THREAD

**Issue by StarBattle08** [jeromexiong/audio_manager#77]
If a current audio file is paused and the app is in background, The audio automatically start upon opening the app to the foreground. And it doesn't continue where the audio was left off, it plays from the beginning.

Apparently it's only happening in release version? i'm not too sure, as it doesn't happen when I'm on debug mode

- audio-manager 0.8.1
- flutter 2.2.3

**Comment by JoelFickson** [comment]
I have come across this as well.

**Comment by jeromexiong** [comment]
i will fix it soon
