### ISSUE TITLE
Play/Pause Not working properly

### ISSUE THREAD

**Issue by mohitdholakia** [jeromexiong/audio_manager#78]
After Pause audio player instance it is not getting played again

method used : **playOrPause**

on every play event below line printed twice

[+6039 ms] V/AudioManagerPlugin(28914): --playOrPause
[  +24 ms] V/AudioManagerPlugin(28914): --playOrPause

**Comment by StarBattle08** [comment]
This happens to me only for the 1st item in the list & if that 1st item is the 1st one to play.

**Comment by jeromexiong** [comment]
this will be fixed soon
