### ISSUE TITLE
audio manager 0.8.2 not working in android 

### ISSUE THREAD

**Issue by mahmed743** [jeromexiong/audio_manager#88]
im add plugin but not working  in Android  , but working good in ios please  help me .

this my version  : 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.6 20G165 darwin-arm, locale en-SD)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by skylastn** [comment]
Same here

**Comment by mahmed743** [comment]
i'm use audio_service: ^0.17.0
