### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by Veerse** [jeromexiong/audio_manager#9]
Hello. Thanks for the great package

However, I'm wondering if there is any simple way to change the package language ? I get controls from control center and callbacks, errors and stuff in chinese

**Comment by jeromexiong** [comment]
Sorry about that, there is no multilingual support at this time. But it doesn't hinder music playing. Chinese is mostly a reminder log

**Comment by Veerse** [comment]
Thanks for the quick answer
It does actually because buttons are in chinese..

<img width="403" alt="notification" src="https://user-images.githubusercontent.com/20816459/77909863-5e39f300-728e-11ea-9e7b-17cdfa721bdc.png">

**Comment by jeromexiong** [comment]
This is a good question, thanks for remindering. I will change the Android notification text to icon and release the patch soon
