### ISSUE TITLE
AudioManagerEvents.error, audio resource loading.....

### ISSUE THREAD

**Issue by skylastn** [jeromexiong/audio_manager#90]
when i try to play video in play button its saying "AudioManagerEvents.error, audio resource loading..... ", and can't listen event 

anyone can help me?

![image](https://user-images.githubusercontent.com/37267553/150351612-af5fe2ea-ed3c-450a-be04-05b6652686fd.png)

**Comment by laxkarparas1** [comment]
Hii @skylastn how did you resolved this issue??
